Added author check against file

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -44,7 +44,10 @@ current_dir() {
     echo "${udir}"
 }
 
-
+strcat() {
+  local IFS=""
+  echo -n "$*"
+}
 # Options {{{
 print=0
 non_ascii_file_names=0
@@ -60,6 +63,7 @@ if [ -f "${cfg_fname}" ]; then
 else
     echo -e "\tConfiguration file not found, using defaults"
 fi
+pkg_dir=$(git rev-parse --show-toplevel)
 if [ "${print}" == 1 ]; then
     echo -e "\tGit pre-commit setup"
     echo -e "\t\tprint=${print}"
@@ -104,18 +108,16 @@ if [ "${non_ascii_file_names}" == 1 ]; then
             wc -c \
         )" != 0
     then
-        cat <<\EOF
-Error: attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
-    exit 1
+        msg=$(strcat \
+            "Error: attempt to add a non-ASCII file name.\n" \
+            "This can cause problems if you want to work with people on\n" \
+            "other platforms. To be portable it is advisable to rename\n" \
+            "the file. If you know what you are doing you can disable\n" \
+            " this check using:\n" \
+            "    git config hooks.allownonascii true\n" \
+        )
+        >&2 echo "${msg}"
+        exit 1
     fi
 fi
 # }}}
@@ -134,10 +136,14 @@ fi
 # }}}
 # Check for Python PEP8 (code style) compliance {{{
 if [ "${pep8}" == 1 ]; then
+    config_fname="${pkg_dir}/.pylintrc"
+    if [ ! -f "${config_fname}" ]; then
+        >&2 echo -e "Pylint config file ${config_fname} not found"
+        exit 1
+    fi
     if [ "${print}" == 1 ]; then
         echo -e "\tValidating Python PEP8 compliance with Pylint"
     fi
-    pkg_dir=$(git rev-parse --show-toplevel)
     python_files=$(git diff --name-only --cached -- *.py)
     pep8_output=""
     # shellcheck disable=SC2068
@@ -145,7 +151,7 @@ if [ "${pep8}" == 1 ]; then
         if [ "${file}" != "" ]; then
             tfile="$(mktemp)"
             file_output=""
-            pylint --rcfile="${pkg_dir}/.pylintrc" -r n "${file}" &> "${tfile}"
+            pylint --rcfile="${config_fname}" -r n "${file}" &> "${tfile}"
             if [ "$?" != 0 ]; then
                 file_output=$(cat "${tfile}")
                 rm -rf "${tfile}"
@@ -156,7 +162,7 @@ if [ "${pep8}" == 1 ]; then
         fi
     done
     if [ "${pep8_output}" != "" ]; then
-        echo -e "${pep8_output}"
+        >&2 echo -e "${pep8_output}"
         exit 1
     fi
     #if [ "${python_files}" != "" ]; then
@@ -166,10 +172,14 @@ fi
 # }}}
 # Check for Python PEP257 (docstring style) compliance {{{
 if [ "${pep257}" == 1 ]; then
+    config_fname="${pkg_dir}/.pydocstyle"
+    if [ ! -f "${config_fname}" ]; then
+        >&2 echo -e "Pydocstyle config file ${config_fname} not found"
+        exit 1
+    fi
     if [ "${print}" == 1 ]; then
         echo -e "\tValidating Python PEP257 compliance with pydocstyle"
     fi
-    pkg_dir=$(git rev-parse --show-toplevel)
     python_files=$(git diff --name-only --cached -- *.py)
     pep257_output=""
     # shellcheck disable=SC2068
@@ -177,7 +187,7 @@ if [ "${pep257}" == 1 ]; then
         if [ "${file}" != "" ]; then
             tfile="$(mktemp)"
             file_output=""
-            pydocsytle --config="${pkg_dir}/.pydocstyle" "${file}" &> "${tfile}"
+            pydocsytle --config="${config_fname}" "${file}" &> "${tfile}"
             if [ "$?" != 0 ]; then
                 file_output=$(cat "${tfile}")
                 rm -rf "${tfile}"
@@ -188,7 +198,7 @@ if [ "${pep257}" == 1 ]; then
         fi
     done
     if [ "${pep257_output}" != "" ]; then
-        echo -e "${pep257_output}"
+        >&2 echo -e "${pep257_output}"
         exit 1
     fi
     #if [ "${python_files}" != "" ]; then
@@ -196,50 +206,51 @@ if [ "${pep257}" == 1 ]; then
     #fi
 fi
 # }}}
-# Check for author/email congruence {{{
+# Check for congruence between author file and Git contact information {{{
 if [ "${email}" == 1 ]; then
-    msg="(work repository)"
-    if [ "${personal_repo}" == 1 ]; then
-        msg="(personal repository)"
+    fname=${pkg_dir}/AUTHORS.rst
+    if [ ! -f "${fname}" ]; then
+        >&2 echo -e "Email check could not be done, ${fname} not found"
+        exit 1
     fi
-    if [ "${print}" == 1 ]; then
-        echo -e "\tValidating author name and email ${msg}"
-    fi
-    if [ "${personal_repo}" == 1 ]; then
-        if [ "${PERSONAL_NAME}" == "" ] || [ "${PERSONAL_EMAIL}" == "" ]; then
-            echo -e "Error: personal information not present"
-            exit 1
+    git_author="$(git config user.name) <$(git config user.email)>"
+    names=$(\
+        grep -E '^\s*.*\s+<.*>\s*$' "${fname}" | \
+        sed -r -e 's/(\s*\*\s+)(.*)/\2/g' | \
+        sed -r -e 's/\s+/ /g' \
+    )
+    names=${names//[$'\t\r\n']}
+    sep=">"
+    found=0
+    while [ "${names}" != "${names#*${sep}}" ]; do
+        name="${names%%${sep}*}${sep}"
+        name="${name## }"
+        echo "|${name}|"
+        if [ "${name}" == "${git_author}" ]; then
+            found=1
+            break
         fi
-        history_name="${PERSONAL_NAME}"
-        history_email="${PERSONAL_EMAIL}"
-    else
-        if [ "${WORK_NAME}" == "" ] || [ "${WORK_EMAIL}" == "" ]; then
-            echo -e "Error: personal information not present"
-            exit 1
-        fi
-        history_name="${WORK_NAME}"
-        history_email="${WORK_EMAIL}"
-    fi
-    current_name=$(git config user.name)
-    current_email=$(git config user.email)
-    if [ "${history_name}" != "${current_name}" ] || \
-        [ "${history_email}" != "${current_email}" ]; then
-        echo -e "Error: incongruent commit author information"
-        echo -e "    Current is ${current_name} <${current_email}>"
-        echo -e "    Reference is ${history_name} <${history_email}>"
+        names="${names#*${sep}}"
+    done
+    if [ "${found}" == 0 ]; then
+        >&2 echo -e "Error: git author ${git_author} not found in ${fname}"
         exit 1
     fi
 fi
 # }}}
 # Check for code "standard" compliance {{{
 if [ "${code_standard}" == 1 ]; then
+    script="${pkg_dir}/bin/check_files_compliance.py"
+    if [ ! -f "${script}" ]; then
+        >&2 echo -e "Error: code compliance script ${script} not found"
+        exit 1
+    fi
     if [ "${print}" == 1 ]; then
         echo -e "\tChecking code standard compliance"
     fi
     files=$(git diff --name-only --cached)
-    pkg_dir=$(git rev-parse --show-toplevel)
-    if ! "${pkg_dir}/bin/check_files_compliance.py" -qstp "${files}"; then
-        echo -e "Error: files do not comply with package code standard"
+    if ! "${script}" -qstp "${files}"; then
+        >&2 echo -e "Error: files do not comply with package code standard"
         exit 1
     fi
 fi
