Fixed selection of Python files

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,9 +1,9 @@
 #!/bin/bash
-# shellcheck disable=SC1090,SC1091
+# shellcheck disable=SC1090,SC1091,SC1117,SC2181
 
 # The MIT License (MIT)
 #
-# Copyright (c) 2013-2018 Pablo Acosta-Serafini
+# Copyright (c) 2013-2019 Pablo Acosta-Serafini
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -52,7 +52,6 @@ strcat() {
 print=0
 non_ascii_file_names=0
 trailing_white_space=0
-pep8=0
 email=0
 personal_repo=0
 code_standard=0
@@ -69,7 +68,6 @@ if [ "${print}" == 1 ]; then
     echo -e "\t\tprint=${print}"
     echo -e "\t\tnon_ascii_file_names=${non_ascii_file_names}"
     echo -e "\t\ttrailing_white_space=${trailing_white_space}"
-    echo -e "\t\tpep8=${pep8}"
     echo -e "\t\tpep257=${pep257}"
     echo -e "\t\temail=${email}"
     echo -e "\t\tpersonal_repo=${personal_repo}"
@@ -135,75 +133,117 @@ if [ "${trailing_white_space}" == 1 ]; then
 fi
 # }}}
 # Check for Python PEP8 (code style) compliance {{{
-if [ "${pep8}" == 1 ]; then
-    config_fname="${pkg_dir}/.pylintrc"
-    if [ ! -f "${config_fname}" ]; then
-        >&2 echo -e "Pylint config file ${config_fname} not found"
-        exit 1
-    fi
-    if [ "${print}" == 1 ]; then
-        echo -e "\tValidating Python PEP8 compliance with Pylint"
-    fi
+if [ "${code_standard}" == 1 ]; then
     python_files=$(git diff --name-only --cached -- *.py)
-    pep8_output=""
-    # shellcheck disable=SC2068
-    for file in ${python_files[@]}; do
-        if [ "${file}" != "" ]; then
-            tfile="$(mktemp)"
-            file_output=""
-            pylint --rcfile="${config_fname}" -r n "${file}" &> "${tfile}"
-            if [ "$?" != 0 ]; then
-                file_output=$(cat "${tfile}")
-                rm -rf "${tfile}"
-            fi
-            if [ "${file_output}" != "" ]; then
-                pep8_output=${pep8_output}"\n"${file_output}
-            fi
+    if [ "|${python_files[*]}|" != "||" ]; then
+        config_fname="${pkg_dir}/.pylintrc"
+        if [ ! -f "${config_fname}" ]; then
+            >&2 echo -e "Pylint config file ${config_fname} not found"
+            exit 1
         fi
-    done
-    if [ "${pep8_output}" != "" ]; then
-        >&2 echo -e "${pep8_output}"
-        exit 1
+        if [ "${print}" == 1 ]; then
+            echo -e "\tValidating Python PEP8 compliance with Pylint"
+        fi
+        python_files=$(git diff --name-only --cached -- *.py)
+        cmd=$(strcat \
+            "from __future__ import print_function;" \
+            "import os;" \
+            "plugin_dir = os.path.join(os.environ.get('REPO_DIR', ''), 'pylint_plugins');" \
+            "print(plugin_dir if os.path.isdir(plugin_dir) else '')" \
+        )
+        PYLINT_PLUGINS_DIR=$(python -c "${cmd}")
+        export PYLINT_PLUGINS_DIR
+        cmd=$(strcat \
+            "from __future__ import print_function;" \
+            "import glob;" \
+            "import os;" \
+            "sdir = os.environ.get('PYLINT_PLUGINS_DIR', '');" \
+            "print(" \
+                "','.join(" \
+                    "[" \
+                        "os.path.basename(fname).replace('.py', '')" \
+                        "for fname in glob.glob(os.path.join(sdir, '*.py'))" \
+                    "]"\
+                ")" \
+                "if sdir else ''" \
+            ")" \
+        )
+        PYLINT_PLUGINS_LIST=$(python -c "${cmd}")
+        export PYLINT_PLUGINS_LIST
+        cmd=$(strcat \
+            "from __future__ import print_function;" \
+            "import os;" \
+            "svar=os.environ.get('PYLINT_PLUGINS_LIST', '');" \
+            "print('--load-plugins='+svar if svar else '')" \
+        )
+        PYLINT_CLI_APPEND=$(python -c "${cmd}")
+        export PYLINT_CLI_APPEND
+        pep8_output=""
+        # shellcheck disable=SC2068
+        for file in ${python_files[@]}; do
+            if [ "${file}" != "" ]; then
+                tfile="$(mktemp)"
+                file_output=""
+                PYTHONPATH="${PYTHONPATH}:${PYLINT_PLUGINS_DIR}" \
+                    pylint \
+                        --rcfile="${config_fname}" \
+                        "${PYLINT_CLI_APPEND}" \
+                        "${file}" &> "${tfile}"
+                if [ "$?" != 0 ]; then
+                    file_output=$(cat "${tfile}")
+                    rm -rf "${tfile}"
+                fi
+                if [ "${file_output}" != "" ]; then
+                    pep8_output=${pep8_output}"\n"${file_output}
+                fi
+            fi
+        done
+        if [ "${pep8_output}" != "" ]; then
+            >&2 echo -e "${pep8_output}"
+            exit 1
+        fi
+        #if [ "${python_files}" != "" ]; then
+        #   echo -e "All Python files are PEP8 compliant"
+        #fi
     fi
-    #if [ "${python_files}" != "" ]; then
-    #   echo -e "All Python files are PEP8 compliant"
-    #fi
 fi
 # }}}
 # Check for Python PEP257 (docstring style) compliance {{{
 if [ "${pep257}" == 1 ]; then
-    config_fname="${pkg_dir}/.pydocstyle"
-    if [ ! -f "${config_fname}" ]; then
-        >&2 echo -e "Pydocstyle config file ${config_fname} not found"
-        exit 1
-    fi
-    if [ "${print}" == 1 ]; then
-        echo -e "\tValidating Python PEP257 compliance with pydocstyle"
-    fi
     python_files=$(git diff --name-only --cached -- *.py)
-    pep257_output=""
-    # shellcheck disable=SC2068
-    for file in ${python_files[@]}; do
-        if [ "${file}" != "" ]; then
-            tfile="$(mktemp)"
-            file_output=""
-            pydocsytle --config="${config_fname}" "${file}" &> "${tfile}"
-            if [ "$?" != 0 ]; then
-                file_output=$(cat "${tfile}")
-                rm -rf "${tfile}"
-            fi
-            if [ "${file_output}" != "" ]; then
-                pep257_output=${pep257_output}"\n"${file_output}
-            fi
+    if [ "|${python_files[*]}|" != "||" ]; then
+        config_fname="${pkg_dir}/.pydocstyle"
+        if [ ! -f "${config_fname}" ]; then
+            >&2 echo -e "Pydocstyle config file ${config_fname} not found"
+            exit 1
         fi
-    done
-    if [ "${pep257_output}" != "" ]; then
-        >&2 echo -e "${pep257_output}"
-        exit 1
+        if [ "${print}" == 1 ]; then
+            echo -e "\tValidating Python PEP257 compliance with pydocstyle"
+        fi
+        pep257_output=""
+        # shellcheck disable=SC2068
+        for file in ${python_files[@]}; do
+            if [ "${file}" != "" ]; then
+                tfile="$(mktemp)"
+                file_output=""
+                pydocstyle --config="${config_fname}" "${file}" &> "${tfile}"
+                if [ "$?" != 0 ]; then
+                    file_output=$(cat "${tfile}")
+                    rm -rf "${tfile}"
+                fi
+                if [ "${file_output}" != "" ]; then
+                    pep257_output=${pep257_output}"\n"${file_output}
+                fi
+            fi
+        done
+        if [ "${pep257_output}" != "" ]; then
+            >&2 echo -e "${pep257_output}"
+            exit 1
+        fi
+        #if [ "${python_files}" != "" ]; then
+        #   echo -e "All Python files are PEP257 compliant"
+        #fi
     fi
-    #if [ "${python_files}" != "" ]; then
-    #   echo -e "All Python files are PEP257 compliant"
-    #fi
 fi
 # }}}
 # Check for congruence between author file and Git contact information {{{
@@ -234,23 +274,6 @@ if [ "${email}" == 1 ]; then
     done
     if [ "${found}" == 0 ]; then
         >&2 echo -e "Error: git author ${git_author} not found in ${fname}"
-        exit 1
-    fi
-fi
-# }}}
-# Check for code "standard" compliance {{{
-if [ "${code_standard}" == 1 ]; then
-    script="${pkg_dir}/bin/check_files_compliance.py"
-    if [ ! -f "${script}" ]; then
-        >&2 echo -e "Error: code compliance script ${script} not found"
-        exit 1
-    fi
-    if [ "${print}" == 1 ]; then
-        echo -e "\tChecking code standard compliance"
-    fi
-    files=$(git diff --name-only --cached)
-    if ! "${script}" -qstp "${files}"; then
-        >&2 echo -e "Error: files do not comply with package code standard"
         exit 1
     fi
 fi
